# === Analysis configuration file ======================================================


# --- Configuration for `seqneut-pipeline` ---------------------------------------------

seqneut-pipeline: seqneut-pipeline

docs: docs

description: |
  # Sequencing-based neutralization assays of human serum samples from the Ellebedy lab with individuals vaccinated either with the 2022-2023 Fluarix egg-based vaccine or with the 2022-2023 mRNA-1010 vaccine, using a ~100 variant library of H3N2 and H1N1 influenza variants. 

  The numerical data and computer code are at [https://github.com/jbloomlab/flu_seqneut_with_Ellebedy_lab](https://github.com/jbloomlab/flu_seqneut_with_Ellebedy_lab)


viral_libraries:
  # The viral library is comprised of the 78 H3 strains in Kikawa et al 2025 plus additional circulating H3 strains from 2023 and strains from pdmH1N1_lib2023_loes.csv 
  H3_H1_ellebedy_library: data/viral_libraries/H3_H1_ellebedy_library.csv
  
viral_strain_plot_order: data/H3_H1_ellebedy_library_strain_order.csv

neut_standard_sets:
  loes2023: data/neut_standard_sets/loes2023_neut_standards.csv

illumina_barcode_parser_params:
  upstream: CCTACAATGTCGGATTTGTATTTAATAG
  downstream: ''
  minq: 20
  upstream_mismatch: 4
  bc_orientation: R2

default_process_plate_qc_thresholds: &default_process_plate_qc_thresholds
  avg_barcode_counts_per_well: 500
  min_neut_standard_frac_per_well: 0.005
  no_serum_per_viral_barcode_filters:
    min_frac: 0.0001
    max_fold_change: 4
    max_wells: 2
  per_neut_standard_barcode_filters:
    min_frac: 0.005
    max_fold_change: 4
    max_wells: 2
  min_neut_standard_count_per_well: 1000
  min_no_serum_count_per_viral_barcode_well: 100
  max_frac_infectivity_per_viral_barcode_well: 3
  min_dilutions_per_barcode_serum_replicate: 6

default_process_plate_curvefit_params: &default_process_plate_curvefit_params
  frac_infectivity_ceiling: 1
  fixtop: [0.6, 1] 
  fixbottom: 0
  fixslope: [0.8, 10]

default_process_plate_curvefit_qc:  &default_process_plate_curvefit_qc
  max_frac_infectivity_at_least: 0.0  # Allow 'completely neutralized' straight lines to be fit
  goodness_of_fit:  # EITHER R2 must be >= min_R2 or RMSD must be <= max_RMSD
    min_R2: 0.5
    max_RMSD: 0.15  # you may be able to increase this to more like 0.1
  serum_replicates_ignore_curvefit_qc: []
  barcode_serum_replicates_ignore_curvefit_qc: []

default_serum_titer_as: midpoint

default_serum_qc_thresholds: &default_serum_qc_thresholds
  min_replicates: 1
  max_fold_change_from_median: 6
  viruses_ignore_qc: []

sera_override_defaults: {}

plates:

  plate1:
    group: EllebedyVaccineCohort
    date: 2025-05-09
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-05-08_plate_mapping_file1.csv
    manual_drops: 
      barcode_wells:
        - [CTCATTACAGAAATTG, A1]
        - [AAAGATAAATTCAAAA, A2]
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1

  plate2:
    group: EllebedyVaccineCohort
    date: 2025-05-29
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-05-29_plate_mapping_file2.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1  

  plate3:
    group: EllebedyVaccineCohort
    date: 2025-05-29
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-05-29_plate_mapping_file3.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CAGTTG # Fwd4
      upstream2_mismatch: 1  

  plate4:
    group: EllebedyVaccineCohort
    date: 2025-05-29
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-05-29_plate_mapping_file4.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GCTACA # Fwd1
      upstream2_mismatch: 1 

  plate5:
    group: EllebedyVaccineCohort
    date: 2025-05-29
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-05-29_plate_mapping_file5.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ATCGAT # Fwd2
      upstream2_mismatch: 1 

  plate6:
    group: EllebedyVaccineCohort
    date: 2025-06-25
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-06-25_plate2.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GCTACA # Fwd1
      upstream2_mismatch: 1 

  plate7:
    group: EllebedyVaccineCohort
    date: 2025-06-25
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-06-25_plate3.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ATCGAT # Fwd2
      upstream2_mismatch: 1 

  plate8:
    group: EllebedyVaccineCohort
    date: 2025-06-25
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-06-25_plate6.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1 

  plate9:
    group: EllebedyVaccineCohort
    date: 2025-06-25
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-06-25_plate7.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CAGTTG # Fwd4
      upstream2_mismatch: 1 

  plate10:
    group: EllebedyVaccineCohort
    date: 2025-06-25
    viral_library: H3_H1_ellebedy_library
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-06-25_plate8.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GTCTAA # Fwd5
      upstream2_mismatch: 1 


miscellaneous_plates:

    20250501_initial_H3H1_ellebedy_library:
      date: 2025-05-01
      viral_library: H3_H1_ellebedy_library
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/H3H1_ellebedy_library_initialPool_samples.csv

    20250509_repool_H3H1_ellebedy_library:
      date: 2025-05-09
      viral_library: H3_H1_ellebedy_library
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/2025-05-08_H3H1_ellebedy_library_repool_samples.csv
      illumina_barcode_parser_params:
          upstream2: CAGTTG # Fwd4
          upstream2_mismatch: 1
